// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pacman.proto
// Protobuf Java Version: 4.28.2

package pacman;

public interface EndGameResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pacman.EndGameResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Indicates if all players have ended the game
   * </pre>
   *
   * <code>bool allPlayersEnded = 1;</code>
   * @return The allPlayersEnded.
   */
  boolean getAllPlayersEnded();
}
