// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pacman.proto
// Protobuf Java Version: 4.28.2

package pacman;

public interface EndGameRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pacman.EndGameRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The name of the player who is ending the game
   * </pre>
   *
   * <code>string playerName = 1;</code>
   * @return The playerName.
   */
  java.lang.String getPlayerName();
  /**
   * <pre>
   * The name of the player who is ending the game
   * </pre>
   *
   * <code>string playerName = 1;</code>
   * @return The bytes for playerName.
   */
  com.google.protobuf.ByteString
      getPlayerNameBytes();
}
