// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pacman.proto
// Protobuf Java Version: 4.28.2

package pacman;

public interface GameStartUpdateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pacman.GameStartUpdate)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Indicates if the game has started
   * </pre>
   *
   * <code>string playerName = 1;</code>
   * @return The playerName.
   */
  java.lang.String getPlayerName();
  /**
   * <pre>
   * Indicates if the game has started
   * </pre>
   *
   * <code>string playerName = 1;</code>
   * @return The bytes for playerName.
   */
  com.google.protobuf.ByteString
      getPlayerNameBytes();
}
