// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pacman.proto
// Protobuf Java Version: 4.28.2

package pacman;

public interface JoinResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pacman.JoinResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <pre>
   * List of current players
   * </pre>
   *
   * <code>repeated string players = 2;</code>
   * @return A list containing the players.
   */
  java.util.List<java.lang.String>
      getPlayersList();
  /**
   * <pre>
   * List of current players
   * </pre>
   *
   * <code>repeated string players = 2;</code>
   * @return The count of players.
   */
  int getPlayersCount();
  /**
   * <pre>
   * List of current players
   * </pre>
   *
   * <code>repeated string players = 2;</code>
   * @param index The index of the element to return.
   * @return The players at the given index.
   */
  java.lang.String getPlayers(int index);
  /**
   * <pre>
   * List of current players
   * </pre>
   *
   * <code>repeated string players = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the players at the given index.
   */
  com.google.protobuf.ByteString
      getPlayersBytes(int index);
}
