// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pacman.proto
// Protobuf Java Version: 4.28.2

package pacman;

/**
 * Protobuf type {@code pacman.JoinResponse}
 */
public final class JoinResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:pacman.JoinResponse)
    JoinResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      JoinResponse.class.getName());
  }
  // Use JoinResponse.newBuilder() to construct.
  private JoinResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private JoinResponse() {
    message_ = "";
    players_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return pacman.Pacman.internal_static_pacman_JoinResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return pacman.Pacman.internal_static_pacman_JoinResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            pacman.JoinResponse.class, pacman.JoinResponse.Builder.class);
  }

  public static final int MESSAGE_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object message_ = "";
  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  @java.lang.Override
  public java.lang.String getMessage() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      message_ = s;
      return s;
    }
  }
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMessageBytes() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      message_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PLAYERS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList players_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <pre>
   * List of current players
   * </pre>
   *
   * <code>repeated string players = 2;</code>
   * @return A list containing the players.
   */
  public com.google.protobuf.ProtocolStringList
      getPlayersList() {
    return players_;
  }
  /**
   * <pre>
   * List of current players
   * </pre>
   *
   * <code>repeated string players = 2;</code>
   * @return The count of players.
   */
  public int getPlayersCount() {
    return players_.size();
  }
  /**
   * <pre>
   * List of current players
   * </pre>
   *
   * <code>repeated string players = 2;</code>
   * @param index The index of the element to return.
   * @return The players at the given index.
   */
  public java.lang.String getPlayers(int index) {
    return players_.get(index);
  }
  /**
   * <pre>
   * List of current players
   * </pre>
   *
   * <code>repeated string players = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the players at the given index.
   */
  public com.google.protobuf.ByteString
      getPlayersBytes(int index) {
    return players_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(message_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, message_);
    }
    for (int i = 0; i < players_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, players_.getRaw(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(message_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, message_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < players_.size(); i++) {
        dataSize += computeStringSizeNoTag(players_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getPlayersList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof pacman.JoinResponse)) {
      return super.equals(obj);
    }
    pacman.JoinResponse other = (pacman.JoinResponse) obj;

    if (!getMessage()
        .equals(other.getMessage())) return false;
    if (!getPlayersList()
        .equals(other.getPlayersList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getMessage().hashCode();
    if (getPlayersCount() > 0) {
      hash = (37 * hash) + PLAYERS_FIELD_NUMBER;
      hash = (53 * hash) + getPlayersList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static pacman.JoinResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static pacman.JoinResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static pacman.JoinResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static pacman.JoinResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static pacman.JoinResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static pacman.JoinResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static pacman.JoinResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static pacman.JoinResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static pacman.JoinResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static pacman.JoinResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static pacman.JoinResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static pacman.JoinResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(pacman.JoinResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code pacman.JoinResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:pacman.JoinResponse)
      pacman.JoinResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pacman.Pacman.internal_static_pacman_JoinResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pacman.Pacman.internal_static_pacman_JoinResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pacman.JoinResponse.class, pacman.JoinResponse.Builder.class);
    }

    // Construct using pacman.JoinResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      message_ = "";
      players_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return pacman.Pacman.internal_static_pacman_JoinResponse_descriptor;
    }

    @java.lang.Override
    public pacman.JoinResponse getDefaultInstanceForType() {
      return pacman.JoinResponse.getDefaultInstance();
    }

    @java.lang.Override
    public pacman.JoinResponse build() {
      pacman.JoinResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public pacman.JoinResponse buildPartial() {
      pacman.JoinResponse result = new pacman.JoinResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(pacman.JoinResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.message_ = message_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        players_.makeImmutable();
        result.players_ = players_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof pacman.JoinResponse) {
        return mergeFrom((pacman.JoinResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(pacman.JoinResponse other) {
      if (other == pacman.JoinResponse.getDefaultInstance()) return this;
      if (!other.getMessage().isEmpty()) {
        message_ = other.message_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.players_.isEmpty()) {
        if (players_.isEmpty()) {
          players_ = other.players_;
          bitField0_ |= 0x00000002;
        } else {
          ensurePlayersIsMutable();
          players_.addAll(other.players_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              message_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();
              ensurePlayersIsMutable();
              players_.add(s);
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object message_ = "";
    /**
     * <code>string message = 1;</code>
     * @return The message.
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string message = 1;</code>
     * @return The bytes for message.
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string message = 1;</code>
     * @param value The message to set.
     * @return This builder for chaining.
     */
    public Builder setMessage(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      message_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string message = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessage() {
      message_ = getDefaultInstance().getMessage();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string message = 1;</code>
     * @param value The bytes for message to set.
     * @return This builder for chaining.
     */
    public Builder setMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      message_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList players_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensurePlayersIsMutable() {
      if (!players_.isModifiable()) {
        players_ = new com.google.protobuf.LazyStringArrayList(players_);
      }
      bitField0_ |= 0x00000002;
    }
    /**
     * <pre>
     * List of current players
     * </pre>
     *
     * <code>repeated string players = 2;</code>
     * @return A list containing the players.
     */
    public com.google.protobuf.ProtocolStringList
        getPlayersList() {
      players_.makeImmutable();
      return players_;
    }
    /**
     * <pre>
     * List of current players
     * </pre>
     *
     * <code>repeated string players = 2;</code>
     * @return The count of players.
     */
    public int getPlayersCount() {
      return players_.size();
    }
    /**
     * <pre>
     * List of current players
     * </pre>
     *
     * <code>repeated string players = 2;</code>
     * @param index The index of the element to return.
     * @return The players at the given index.
     */
    public java.lang.String getPlayers(int index) {
      return players_.get(index);
    }
    /**
     * <pre>
     * List of current players
     * </pre>
     *
     * <code>repeated string players = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the players at the given index.
     */
    public com.google.protobuf.ByteString
        getPlayersBytes(int index) {
      return players_.getByteString(index);
    }
    /**
     * <pre>
     * List of current players
     * </pre>
     *
     * <code>repeated string players = 2;</code>
     * @param index The index to set the value at.
     * @param value The players to set.
     * @return This builder for chaining.
     */
    public Builder setPlayers(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensurePlayersIsMutable();
      players_.set(index, value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * List of current players
     * </pre>
     *
     * <code>repeated string players = 2;</code>
     * @param value The players to add.
     * @return This builder for chaining.
     */
    public Builder addPlayers(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensurePlayersIsMutable();
      players_.add(value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * List of current players
     * </pre>
     *
     * <code>repeated string players = 2;</code>
     * @param values The players to add.
     * @return This builder for chaining.
     */
    public Builder addAllPlayers(
        java.lang.Iterable<java.lang.String> values) {
      ensurePlayersIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, players_);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * List of current players
     * </pre>
     *
     * <code>repeated string players = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPlayers() {
      players_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000002);;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * List of current players
     * </pre>
     *
     * <code>repeated string players = 2;</code>
     * @param value The bytes of the players to add.
     * @return This builder for chaining.
     */
    public Builder addPlayersBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensurePlayersIsMutable();
      players_.add(value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:pacman.JoinResponse)
  }

  // @@protoc_insertion_point(class_scope:pacman.JoinResponse)
  private static final pacman.JoinResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new pacman.JoinResponse();
  }

  public static pacman.JoinResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<JoinResponse>
      PARSER = new com.google.protobuf.AbstractParser<JoinResponse>() {
    @java.lang.Override
    public JoinResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<JoinResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<JoinResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public pacman.JoinResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

