// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pacman.proto
// Protobuf Java Version: 4.28.2

package pacman;

public interface LobbyUpdateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pacman.LobbyUpdate)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string playerName = 1;</code>
   * @return The playerName.
   */
  java.lang.String getPlayerName();
  /**
   * <code>string playerName = 1;</code>
   * @return The bytes for playerName.
   */
  com.google.protobuf.ByteString
      getPlayerNameBytes();

  /**
   * <pre>
   * True if joining, false if leaving
   * </pre>
   *
   * <code>bool isJoining = 2;</code>
   * @return The isJoining.
   */
  boolean getIsJoining();
}
