// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pacman.proto
// Protobuf Java Version: 4.28.2

package pacman;

public interface ScoreUpdateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pacman.ScoreUpdate)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string player_name = 1;</code>
   * @return The playerName.
   */
  java.lang.String getPlayerName();
  /**
   * <code>string player_name = 1;</code>
   * @return The bytes for playerName.
   */
  com.google.protobuf.ByteString
      getPlayerNameBytes();

  /**
   * <code>int32 score = 2;</code>
   * @return The score.
   */
  int getScore();
}
