// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pacman.proto
// Protobuf Java Version: 4.28.2

package pacman;

public interface ScoreHistoryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pacman.ScoreHistory)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Name of the player
   * </pre>
   *
   * <code>string playerName = 1;</code>
   * @return The playerName.
   */
  java.lang.String getPlayerName();
  /**
   * <pre>
   * Name of the player
   * </pre>
   *
   * <code>string playerName = 1;</code>
   * @return The bytes for playerName.
   */
  com.google.protobuf.ByteString
      getPlayerNameBytes();

  /**
   * <pre>
   * Player's score
   * </pre>
   *
   * <code>int32 score = 2;</code>
   * @return The score.
   */
  int getScore();
}
