// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pacman.proto
// Protobuf Java Version: 4.28.2

package pacman;

/**
 * <pre>
 * New response message for top scores
 * </pre>
 *
 * Protobuf type {@code pacman.TopScoresResponse}
 */
public final class TopScoresResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:pacman.TopScoresResponse)
    TopScoresResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      TopScoresResponse.class.getName());
  }
  // Use TopScoresResponse.newBuilder() to construct.
  private TopScoresResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private TopScoresResponse() {
    scores_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return pacman.Pacman.internal_static_pacman_TopScoresResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return pacman.Pacman.internal_static_pacman_TopScoresResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            pacman.TopScoresResponse.class, pacman.TopScoresResponse.Builder.class);
  }

  public static final int SCORES_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<pacman.ScoreHistory> scores_;
  /**
   * <pre>
   * List of top scores
   * </pre>
   *
   * <code>repeated .pacman.ScoreHistory scores = 1;</code>
   */
  @java.lang.Override
  public java.util.List<pacman.ScoreHistory> getScoresList() {
    return scores_;
  }
  /**
   * <pre>
   * List of top scores
   * </pre>
   *
   * <code>repeated .pacman.ScoreHistory scores = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends pacman.ScoreHistoryOrBuilder> 
      getScoresOrBuilderList() {
    return scores_;
  }
  /**
   * <pre>
   * List of top scores
   * </pre>
   *
   * <code>repeated .pacman.ScoreHistory scores = 1;</code>
   */
  @java.lang.Override
  public int getScoresCount() {
    return scores_.size();
  }
  /**
   * <pre>
   * List of top scores
   * </pre>
   *
   * <code>repeated .pacman.ScoreHistory scores = 1;</code>
   */
  @java.lang.Override
  public pacman.ScoreHistory getScores(int index) {
    return scores_.get(index);
  }
  /**
   * <pre>
   * List of top scores
   * </pre>
   *
   * <code>repeated .pacman.ScoreHistory scores = 1;</code>
   */
  @java.lang.Override
  public pacman.ScoreHistoryOrBuilder getScoresOrBuilder(
      int index) {
    return scores_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < scores_.size(); i++) {
      output.writeMessage(1, scores_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < scores_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, scores_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof pacman.TopScoresResponse)) {
      return super.equals(obj);
    }
    pacman.TopScoresResponse other = (pacman.TopScoresResponse) obj;

    if (!getScoresList()
        .equals(other.getScoresList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getScoresCount() > 0) {
      hash = (37 * hash) + SCORES_FIELD_NUMBER;
      hash = (53 * hash) + getScoresList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static pacman.TopScoresResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static pacman.TopScoresResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static pacman.TopScoresResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static pacman.TopScoresResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static pacman.TopScoresResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static pacman.TopScoresResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static pacman.TopScoresResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static pacman.TopScoresResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static pacman.TopScoresResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static pacman.TopScoresResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static pacman.TopScoresResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static pacman.TopScoresResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(pacman.TopScoresResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * New response message for top scores
   * </pre>
   *
   * Protobuf type {@code pacman.TopScoresResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:pacman.TopScoresResponse)
      pacman.TopScoresResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pacman.Pacman.internal_static_pacman_TopScoresResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pacman.Pacman.internal_static_pacman_TopScoresResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pacman.TopScoresResponse.class, pacman.TopScoresResponse.Builder.class);
    }

    // Construct using pacman.TopScoresResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (scoresBuilder_ == null) {
        scores_ = java.util.Collections.emptyList();
      } else {
        scores_ = null;
        scoresBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return pacman.Pacman.internal_static_pacman_TopScoresResponse_descriptor;
    }

    @java.lang.Override
    public pacman.TopScoresResponse getDefaultInstanceForType() {
      return pacman.TopScoresResponse.getDefaultInstance();
    }

    @java.lang.Override
    public pacman.TopScoresResponse build() {
      pacman.TopScoresResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public pacman.TopScoresResponse buildPartial() {
      pacman.TopScoresResponse result = new pacman.TopScoresResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(pacman.TopScoresResponse result) {
      if (scoresBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          scores_ = java.util.Collections.unmodifiableList(scores_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.scores_ = scores_;
      } else {
        result.scores_ = scoresBuilder_.build();
      }
    }

    private void buildPartial0(pacman.TopScoresResponse result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof pacman.TopScoresResponse) {
        return mergeFrom((pacman.TopScoresResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(pacman.TopScoresResponse other) {
      if (other == pacman.TopScoresResponse.getDefaultInstance()) return this;
      if (scoresBuilder_ == null) {
        if (!other.scores_.isEmpty()) {
          if (scores_.isEmpty()) {
            scores_ = other.scores_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureScoresIsMutable();
            scores_.addAll(other.scores_);
          }
          onChanged();
        }
      } else {
        if (!other.scores_.isEmpty()) {
          if (scoresBuilder_.isEmpty()) {
            scoresBuilder_.dispose();
            scoresBuilder_ = null;
            scores_ = other.scores_;
            bitField0_ = (bitField0_ & ~0x00000001);
            scoresBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getScoresFieldBuilder() : null;
          } else {
            scoresBuilder_.addAllMessages(other.scores_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              pacman.ScoreHistory m =
                  input.readMessage(
                      pacman.ScoreHistory.parser(),
                      extensionRegistry);
              if (scoresBuilder_ == null) {
                ensureScoresIsMutable();
                scores_.add(m);
              } else {
                scoresBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<pacman.ScoreHistory> scores_ =
      java.util.Collections.emptyList();
    private void ensureScoresIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        scores_ = new java.util.ArrayList<pacman.ScoreHistory>(scores_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        pacman.ScoreHistory, pacman.ScoreHistory.Builder, pacman.ScoreHistoryOrBuilder> scoresBuilder_;

    /**
     * <pre>
     * List of top scores
     * </pre>
     *
     * <code>repeated .pacman.ScoreHistory scores = 1;</code>
     */
    public java.util.List<pacman.ScoreHistory> getScoresList() {
      if (scoresBuilder_ == null) {
        return java.util.Collections.unmodifiableList(scores_);
      } else {
        return scoresBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * List of top scores
     * </pre>
     *
     * <code>repeated .pacman.ScoreHistory scores = 1;</code>
     */
    public int getScoresCount() {
      if (scoresBuilder_ == null) {
        return scores_.size();
      } else {
        return scoresBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * List of top scores
     * </pre>
     *
     * <code>repeated .pacman.ScoreHistory scores = 1;</code>
     */
    public pacman.ScoreHistory getScores(int index) {
      if (scoresBuilder_ == null) {
        return scores_.get(index);
      } else {
        return scoresBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * List of top scores
     * </pre>
     *
     * <code>repeated .pacman.ScoreHistory scores = 1;</code>
     */
    public Builder setScores(
        int index, pacman.ScoreHistory value) {
      if (scoresBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureScoresIsMutable();
        scores_.set(index, value);
        onChanged();
      } else {
        scoresBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * List of top scores
     * </pre>
     *
     * <code>repeated .pacman.ScoreHistory scores = 1;</code>
     */
    public Builder setScores(
        int index, pacman.ScoreHistory.Builder builderForValue) {
      if (scoresBuilder_ == null) {
        ensureScoresIsMutable();
        scores_.set(index, builderForValue.build());
        onChanged();
      } else {
        scoresBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * List of top scores
     * </pre>
     *
     * <code>repeated .pacman.ScoreHistory scores = 1;</code>
     */
    public Builder addScores(pacman.ScoreHistory value) {
      if (scoresBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureScoresIsMutable();
        scores_.add(value);
        onChanged();
      } else {
        scoresBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * List of top scores
     * </pre>
     *
     * <code>repeated .pacman.ScoreHistory scores = 1;</code>
     */
    public Builder addScores(
        int index, pacman.ScoreHistory value) {
      if (scoresBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureScoresIsMutable();
        scores_.add(index, value);
        onChanged();
      } else {
        scoresBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * List of top scores
     * </pre>
     *
     * <code>repeated .pacman.ScoreHistory scores = 1;</code>
     */
    public Builder addScores(
        pacman.ScoreHistory.Builder builderForValue) {
      if (scoresBuilder_ == null) {
        ensureScoresIsMutable();
        scores_.add(builderForValue.build());
        onChanged();
      } else {
        scoresBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * List of top scores
     * </pre>
     *
     * <code>repeated .pacman.ScoreHistory scores = 1;</code>
     */
    public Builder addScores(
        int index, pacman.ScoreHistory.Builder builderForValue) {
      if (scoresBuilder_ == null) {
        ensureScoresIsMutable();
        scores_.add(index, builderForValue.build());
        onChanged();
      } else {
        scoresBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * List of top scores
     * </pre>
     *
     * <code>repeated .pacman.ScoreHistory scores = 1;</code>
     */
    public Builder addAllScores(
        java.lang.Iterable<? extends pacman.ScoreHistory> values) {
      if (scoresBuilder_ == null) {
        ensureScoresIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, scores_);
        onChanged();
      } else {
        scoresBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * List of top scores
     * </pre>
     *
     * <code>repeated .pacman.ScoreHistory scores = 1;</code>
     */
    public Builder clearScores() {
      if (scoresBuilder_ == null) {
        scores_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        scoresBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * List of top scores
     * </pre>
     *
     * <code>repeated .pacman.ScoreHistory scores = 1;</code>
     */
    public Builder removeScores(int index) {
      if (scoresBuilder_ == null) {
        ensureScoresIsMutable();
        scores_.remove(index);
        onChanged();
      } else {
        scoresBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * List of top scores
     * </pre>
     *
     * <code>repeated .pacman.ScoreHistory scores = 1;</code>
     */
    public pacman.ScoreHistory.Builder getScoresBuilder(
        int index) {
      return getScoresFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * List of top scores
     * </pre>
     *
     * <code>repeated .pacman.ScoreHistory scores = 1;</code>
     */
    public pacman.ScoreHistoryOrBuilder getScoresOrBuilder(
        int index) {
      if (scoresBuilder_ == null) {
        return scores_.get(index);  } else {
        return scoresBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * List of top scores
     * </pre>
     *
     * <code>repeated .pacman.ScoreHistory scores = 1;</code>
     */
    public java.util.List<? extends pacman.ScoreHistoryOrBuilder> 
         getScoresOrBuilderList() {
      if (scoresBuilder_ != null) {
        return scoresBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(scores_);
      }
    }
    /**
     * <pre>
     * List of top scores
     * </pre>
     *
     * <code>repeated .pacman.ScoreHistory scores = 1;</code>
     */
    public pacman.ScoreHistory.Builder addScoresBuilder() {
      return getScoresFieldBuilder().addBuilder(
          pacman.ScoreHistory.getDefaultInstance());
    }
    /**
     * <pre>
     * List of top scores
     * </pre>
     *
     * <code>repeated .pacman.ScoreHistory scores = 1;</code>
     */
    public pacman.ScoreHistory.Builder addScoresBuilder(
        int index) {
      return getScoresFieldBuilder().addBuilder(
          index, pacman.ScoreHistory.getDefaultInstance());
    }
    /**
     * <pre>
     * List of top scores
     * </pre>
     *
     * <code>repeated .pacman.ScoreHistory scores = 1;</code>
     */
    public java.util.List<pacman.ScoreHistory.Builder> 
         getScoresBuilderList() {
      return getScoresFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        pacman.ScoreHistory, pacman.ScoreHistory.Builder, pacman.ScoreHistoryOrBuilder> 
        getScoresFieldBuilder() {
      if (scoresBuilder_ == null) {
        scoresBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            pacman.ScoreHistory, pacman.ScoreHistory.Builder, pacman.ScoreHistoryOrBuilder>(
                scores_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        scores_ = null;
      }
      return scoresBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:pacman.TopScoresResponse)
  }

  // @@protoc_insertion_point(class_scope:pacman.TopScoresResponse)
  private static final pacman.TopScoresResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new pacman.TopScoresResponse();
  }

  public static pacman.TopScoresResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TopScoresResponse>
      PARSER = new com.google.protobuf.AbstractParser<TopScoresResponse>() {
    @java.lang.Override
    public TopScoresResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<TopScoresResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TopScoresResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public pacman.TopScoresResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

