// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pacman.proto
// Protobuf Java Version: 4.28.2

package pacman;

public interface TopScoresRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pacman.TopScoresRequest)
    com.google.protobuf.MessageOrBuilder {
}
